name: ramp-map-estimation
channels:
  - conda-forge
dependencies:
  - joblib
  - matplotlib
  - numpy
  - pandas
  - scikit-learn>=1.4
  - pytables
  - pip
  - pip:
    - ramp-workflow
    - osfclient
    - physiocurve
